# travis-ci.org build & test configuration
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

env:
  # pip install matplotlib=1.0 doesn't work
#  - MPL_VERSION=1.0
  - MPL_VERSION=1.1
  - MPL_VERSION=1.2

matrix:
  exclude:
    # matplotlib 1.1 doesn't support Python 3
    - python: "3.2"
      env: MPL_VERSION=1.1


install:
#  - time sudo apt-get update -qq
#  - time sudo apt-get install -qq python-matplotlib
  - time pip install --use-mirrors pytest
  # For Python 2 it is required to install pyparsing 1.5.7 (see http://pyparsing.wikispaces.com)
  # - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then export PYPARSING_PIP="==1.5.7"; fi
  # - time pip install --use-mirrors pyparsing$PYPARSING_PIP
  - time pip install --use-mirrors sphinx
  # Install matplotlib
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '2' ]]; then time pip install --use-mirrors matplotlib==$MPL_VERSION; fi
  # For Python 3 travis-ci apparently doesn't have numpy pre-installed at the moment
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '3' ]]; then time pip install --use-mirrors numpy; fi

script:
  # see https://github.com/leejjoon/pyregion/pull/17#issuecomment-14292168
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '3' ]]; then time pip install git+git://github.com/matplotlib/matplotlib.git@v1.2.x; fi
  # This is really part of the install phase.
  # We put it here to avoid the 15 min travis-ci timeout for the install phase
  - time pip install --use-mirrors astropy
  - time pip install --use-mirrors git+git://github.com/leejjoon/pywcsgrid2.git@master #pywcsgrid2

  # Install and test pyregion
  - python setup.py install
  - python test.py
  - cd doc
  - python make.py
  # TODO Run examples and check output (they first need to be made into unit tests)
